"""
neo_tool_library.py — BlackBugsAI NEO Tool Library v2.1
Self-tools + GitHub integration + OSINT (Sherlock) + 39 built-in tools
"""
from __future__ import annotations
import os, sys, json, time, re, subprocess, sqlite3
from pathlib import Path
from typing import Optional, Callable

BASE_DIR  = Path(__file__).parent
NEO_DIR   = BASE_DIR / "neo_workspace"
TOOLS_DIR = NEO_DIR / "tools"
OSINT_DIR = NEO_DIR / "osint"

for _d in (NEO_DIR, TOOLS_DIR, OSINT_DIR):
    _d.mkdir(parents=True, exist_ok=True)


_T = {}  # name -> (description, code)

_T['self_create_tool'] = (
    'NEO создаёт новый инструмент через LLM или устанавливает с GitHub (если передан url)',
    "def run_tool(inputs):\n    import os, sys\n    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n    name = inputs.get('tool_name', '').strip()\n    desc = inputs.get('description', '').strip()\n    example = inputs.get('example_inputs', {})\n    url = inputs.get('url', inputs.get('github_url', '')).strip()\n    if not name:\n        return {'ok': False, 'output': 'Нужен tool_name', 'files': [], 'error': 'missing'}\n    if url and 'github.com' in url:\n        try:\n            from agent_neo import install_github_as_tool\n            ok, tname, err = install_github_as_tool(\n                url=url, tool_name=name,\n                description=desc or ('GitHub: ' + url),\n                on_status=lambda m: print(m)\n            )\n            if ok:\n                return {'ok': True, 'output': 'Инструмент ' + tname + ' установлен из ' + url, 'files': [], 'error': ''}\n            return {'ok': False, 'output': 'Ошибка: ' + err, 'files': [], 'error': err}\n        except Exception as e:\n            return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}\n    if not desc:\n        return {'ok': False, 'output': 'Нужен description', 'files': [], 'error': 'missing'}\n    try:\n        from agent_neo import generate_tool\n        ok, err = generate_tool(name, desc, example, on_status=lambda m: print(m))\n        if ok:\n            return {'ok': True, 'output': 'Инструмент ' + name + ' создан!', 'files': [], 'error': ''}\n        return {'ok': False, 'output': 'Не удалось: ' + err, 'files': [], 'error': err}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['self_list_tools'] = (
    'Показывает список всех доступных инструментов NEO',
    "def run_tool(inputs):\n    import os, sys\n    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n    try:\n        from agent_neo import list_tools\n        tools = list_tools()\n        if not tools:\n            return {'ok': True, 'output': 'Инструментов пока нет.', 'files': [], 'error': ''}\n        header = 'Инструменты NEO (' + str(len(tools)) + ' шт.):'\n        lines = [header]\n        for t in tools:\n            tag = 'встроенный' if t.get('builtin') else 'динамический'\n            lines.append('  ' + t['name'] + ' [' + tag + ']: ' + t.get('description','')[:60])\n        return {'ok': True, 'output': chr(10).join(lines), 'files': [], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['self_delete_tool'] = (
    'Удаляет инструмент из реестра NEO',
    "def run_tool(inputs):\n    import os, sys, sqlite3\n    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n    name = inputs.get('tool_name','').strip()\n    if not name:\n        return {'ok': False, 'output': 'Нужен tool_name', 'files': [], 'error': 'missing'}\n    try:\n        from agent_neo import TOOLS_DB, TOOLS_DIR\n        db = sqlite3.connect(str(TOOLS_DB))\n        db.execute('DELETE FROM tools WHERE name=?', (name,))\n        db.commit(); db.close()\n        tf = TOOLS_DIR / (name + '.py')\n        if tf.exists(): tf.unlink()\n        return {'ok': True, 'output': 'Инструмент ' + name + ' удалён.', 'files': [], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['github_clone'] = (
    'Клонирует репозиторий с GitHub',
    "def run_tool(inputs):\n    import subprocess, os, shutil\n    from pathlib import Path\n    url = inputs.get('url','').strip()\n    output_dir = inputs.get('output_dir', '/tmp')\n    branch = inputs.get('branch','')\n    if not url:\n        return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    name = url.rstrip('/').split('/')[-1].replace('.git','')\n    dest = str(Path(output_dir) / name)\n    if os.path.exists(dest): shutil.rmtree(dest)\n    cmd = ['git','clone','--depth=1']\n    if branch: cmd += ['--branch', branch]\n    cmd += [url, dest]\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8','cp1251','latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    r = subprocess.run(cmd, capture_output=True, timeout=120)\n    out = _d(r.stdout) + _d(r.stderr)\n    if r.returncode == 0:\n        cnt = sum(1 for p in Path(dest).rglob('*') if p.is_file())\n        return {'ok': True, 'output': 'Клонировано в ' + dest + ' (' + str(cnt) + ' файлов)', 'files': [dest], 'error': ''}\n    return {'ok': False, 'output': out, 'files': [], 'error': out}"
)

_T['github_install_tool'] = (
    'Клонирует GitHub репо, устанавливает зависимости, создаёт LLM-обёртку и регистрирует как инструмент NEO',
    "def run_tool(inputs):\n    import os, sys\n    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n    url = inputs.get('url', inputs.get('repo_url', inputs.get('github_url', ''))).strip()\n    tool_name = inputs.get('tool_name', '').strip()\n    desc = inputs.get('description', '').strip()\n    entry_cmd = inputs.get('entry_cmd', '').strip()\n    if not url:\n        return {'ok': False, 'output': 'Нужен url репозитория GitHub', 'files': [], 'error': 'missing'}\n    if not url.startswith(('http://','https://')):\n        url = 'https://github.com/' + url.lstrip('/')\n    try:\n        from agent_neo import install_github_as_tool\n        ok, name, err = install_github_as_tool(\n            url=url, tool_name=tool_name, description=desc,\n            entry_cmd=entry_cmd, on_status=lambda m: print(m)\n        )\n        if ok:\n            return {'ok': True, 'output': 'Установлен: ' + name + ' из ' + url, 'files': [], 'error': ''}\n        return {'ok': False, 'output': 'Ошибка: ' + err, 'files': [], 'error': err}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['pip_install'] = (
    'Устанавливает Python пакет(ы) через pip',
    "def run_tool(inputs):\n    import subprocess, sys\n    pkgs = inputs.get('packages', inputs.get('package',''))\n    if isinstance(pkgs, list): pkgs = ' '.join(pkgs)\n    pkgs = str(pkgs).strip()\n    if not pkgs:\n        return {'ok': False, 'output': 'Нужен packages', 'files': [], 'error': 'missing'}\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8','cp1251','latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    r = subprocess.run([sys.executable,'-m','pip','install','--break-system-packages','-q']+pkgs.split(),\n                       capture_output=True, timeout=180)\n    out = _d(r.stdout)+_d(r.stderr)\n    ok = r.returncode == 0\n    msg = ('OK: ' if ok else 'FAIL: ') + pkgs + chr(10) + out[:500]\n    return {'ok': ok, 'output': msg, 'files': [], 'error': '' if ok else out[:300]}"
)

_T['osint_sherlock'] = (
    'Sherlock OSINT — поиск аккаунтов по username на 300+ платформах (только публичные данные)',
    "def run_tool(inputs):\n    import subprocess, sys, os\n    from pathlib import Path\n    username   = inputs.get('username','').strip()\n    output_dir = inputs.get('output_dir','/tmp')\n    timeout    = int(inputs.get('timeout',120))\n    if not username:\n        return {'ok': False, 'output': 'Нужен username', 'files': [], 'error': 'missing'}\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8','cp1251','latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    sherlock_dir = Path(__file__).parent.parent / 'neo_workspace' / 'osint' / 'sherlock'\n    if not sherlock_dir.exists():\n        print('Устанавливаю Sherlock...')\n        r = subprocess.run(['git','clone','--depth=1',\n                            'https://github.com/sherlock-project/sherlock.git',\n                            str(sherlock_dir)], capture_output=True, timeout=120)\n        if r.returncode != 0:\n            r2 = subprocess.run([sys.executable,'-m','pip','install','sherlock-project',\n                                  '-q','--break-system-packages'], capture_output=True, timeout=180)\n            if r2.returncode != 0:\n                return {'ok': False, 'output': 'Не удалось установить Sherlock: ' + _d(r.stderr), 'files': [], 'error': 'install_failed'}\n        req = sherlock_dir / 'requirements.txt'\n        if req.exists():\n            subprocess.run([sys.executable,'-m','pip','install','-r',str(req),\n                            '-q','--break-system-packages'], capture_output=True, timeout=180)\n    out_file = Path(output_dir) / ('sherlock_' + username + '.txt')\n    entry = sherlock_dir / 'sherlock' / 'sherlock.py'\n    if not entry.exists(): entry = sherlock_dir / 'sherlock.py'\n    if entry.exists():\n        cmd = [sys.executable, str(entry), username, '--output', str(out_file), '--timeout','5','--print-found']\n    else:\n        cmd = [sys.executable,'-m','sherlock', username, '--output', str(out_file), '--timeout','5','--print-found']\n    r = subprocess.run(cmd, capture_output=True, timeout=timeout)\n    raw = _d(r.stdout) + _d(r.stderr)\n    found = [l for l in raw.splitlines() if '[+]' in l]\n    header = 'Sherlock @' + username + chr(10) + chr(10) + 'Найдено: ' + str(len(found)) + chr(10) + chr(10)\n    text = header + chr(10).join(found[:50])\n    if not found: text = text + chr(10) + raw[:500]\n    files = [str(out_file)] if out_file.exists() else []\n    return {'ok': bool(found), 'output': text, 'files': files, 'error': ''}"
)

_T['osint_username_search'] = (
    'OSINT: поиск username на популярных платформах (публичные профили)',
    "def run_tool(inputs):\n    import urllib.request\n    from pathlib import Path\n    username   = inputs.get('username','').strip()\n    output_dir = inputs.get('output_dir','/tmp')\n    if not username:\n        return {'ok': False, 'output': 'Нужен username', 'files': [], 'error': 'missing'}\n    platforms = [\n        ('GitHub',    'https://github.com/' + username),\n        ('Twitter/X', 'https://twitter.com/' + username),\n        ('Reddit',    'https://www.reddit.com/user/' + username),\n        ('TikTok',    'https://www.tiktok.com/@' + username),\n        ('YouTube',   'https://www.youtube.com/@' + username),\n        ('Twitch',    'https://www.twitch.tv/' + username),\n        ('Telegram',  'https://t.me/' + username),\n        ('GitLab',    'https://gitlab.com/' + username),\n        ('Medium',    'https://medium.com/@' + username),\n        ('Dev.to',    'https://dev.to/' + username),\n    ]\n    found = []; miss = []\n    for p, url in platforms:\n        try:\n            req = urllib.request.Request(url, headers={'User-Agent':'Mozilla/5.0'})\n            with urllib.request.urlopen(req, timeout=8) as r:\n                if r.getcode() == 200: found.append('[+] ' + p + ': ' + url)\n        except: miss.append('[-] ' + p)\n    out_file = Path(output_dir) / ('osint_u_' + username + '.txt')\n    sep = chr(10)\n    text = 'OSINT @' + username + sep + sep + sep.join(found) + sep + 'Не найдено: ' + str(len(miss))\n    out_file.write_text(text, encoding='utf-8')\n    return {'ok': bool(found), 'output': text, 'files': [str(out_file)], 'error': ''}"
)

_T['osint_site_search'] = (
    'OSINT: анализ домена — IP, HTTP заголовки, WHOIS',
    "def run_tool(inputs):\n    import urllib.request, subprocess, socket\n    from pathlib import Path\n    domain = inputs.get('domain', inputs.get('url','')).strip()\n    domain = domain.replace('https://','').replace('http://','').split('/')[0]\n    output_dir = inputs.get('output_dir','/tmp')\n    if not domain:\n        return {'ok': False, 'output': 'Нужен domain', 'files': [], 'error': 'missing'}\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8','cp1251','latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    sep = chr(10)\n    lines = ['OSINT Domain: ' + domain]\n    try:\n        lines.append('IP: ' + socket.gethostbyname(domain))\n    except Exception as e:\n        lines.append('DNS err: ' + str(e))\n    try:\n        req = urllib.request.Request('https://' + domain, headers={'User-Agent':'Mozilla/5.0'})\n        with urllib.request.urlopen(req, timeout=10) as r:\n            for k in ('Server','X-Powered-By','Content-Type'):\n                v = r.headers.get(k)\n                if v: lines.append(k + ': ' + v)\n    except Exception as e:\n        lines.append('HTTP: ' + str(e))\n    r = subprocess.run(['whois', domain], capture_output=True, timeout=20)\n    if r.returncode == 0: lines.append(sep + 'WHOIS:' + sep + _d(r.stdout)[:500])\n    text = sep.join(lines)\n    out_file = Path(output_dir) / ('osint_' + domain + '.txt')\n    out_file.write_text(text, encoding='utf-8')\n    return {'ok': True, 'output': text, 'files': [str(out_file)], 'error': ''}"
)

_T['python_eval'] = (
    'Выполнить Python-код в subprocess',
    "def run_tool(inputs):\n    import subprocess, sys, tempfile, os\n    code = inputs.get('code', inputs.get('script','')).strip()\n    output_dir = inputs.get('output_dir','/tmp')\n    if not code:\n        return {'ok': False, 'output': 'Нужен code', 'files': [], 'error': 'missing'}\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8','cp1251','latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    with tempfile.NamedTemporaryFile('w',suffix='.py',delete=False,encoding='utf-8') as f:\n        f.write(code); tmp=f.name\n    try:\n        r = subprocess.run([sys.executable,tmp], capture_output=True, timeout=30, cwd=output_dir)\n        out = _d(r.stdout)+_d(r.stderr)\n        return {'ok': r.returncode==0, 'output': out.strip()[:3000], 'files': [], 'error': _d(r.stderr) if r.returncode else ''}\n    finally:\n        try: os.unlink(tmp)\n        except: pass"
)

_T['web_scraper'] = (
    'Скачать и очистить текст с веб-страницы',
    "def run_tool(inputs):\n    import urllib.request, re\n    from pathlib import Path\n    url = inputs.get('url','').strip()\n    output_dir = inputs.get('output_dir','/tmp')\n    if not url:\n        return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    try:\n        req = urllib.request.Request(url, headers={'User-Agent':'Mozilla/5.0'})\n        with urllib.request.urlopen(req, timeout=15) as r:\n            html = r.read(100000).decode('utf-8','replace')\n        text = re.sub(r'<[^>]+>',' ',html)\n        text = re.sub(r' +',' ',text).strip()[:5000]\n        out = Path(output_dir) / ('scraped_' + str(abs(hash(url))%99999) + '.txt')\n        out.write_text(text, encoding='utf-8')\n        return {'ok': True, 'output': text[:2000], 'files': [str(out)], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['file_read'] = (
    'Прочитать содержимое файла',
    "def run_tool(inputs):\n    import os\n    path = inputs.get('path','').strip()\n    if not path or not os.path.exists(path):\n        return {'ok': False, 'output': 'Не найден: ' + path, 'files': [], 'error': 'not_found'}\n    if os.path.isdir(path):\n        files = os.listdir(path)[:30]\n        return {'ok': True, 'output': 'Директория: ' + ', '.join(files), 'files': [], 'error': ''}\n    try:\n        for enc in ('utf-8','cp1251','latin-1'):\n            try:\n                content = open(path, encoding=enc).read()\n                return {'ok': True, 'output': content[:5000], 'files': [path], 'error': ''}\n            except UnicodeDecodeError: continue\n        return {'ok': False, 'output': 'Не удалось декодировать', 'files': [], 'error': 'decode'}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['file_write'] = (
    'Записать текст в файл',
    "def run_tool(inputs):\n    import os, time\n    from pathlib import Path\n    path = inputs.get('path','').strip()\n    content = inputs.get('content','')\n    output_dir = inputs.get('output_dir','/tmp')\n    if not path: path = str(Path(output_dir) / ('out_' + str(int(time.time())) + '.txt'))\n    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)\n    Path(path).write_text(str(content), encoding='utf-8')\n    return {'ok': True, 'output': 'Записано: ' + path, 'files': [path], 'error': ''}"
)

_T['zip_extractor'] = (
    'Извлечь содержимое ZIP-архива',
    "def run_tool(inputs):\n    import zipfile, os\n    from pathlib import Path\n    path = inputs.get('path', inputs.get('file_path','')).strip()\n    output_dir = inputs.get('output_dir','/tmp')\n    if not path or not os.path.exists(path):\n        return {'ok': False, 'output': 'Не найден: ' + path, 'files': [], 'error': 'not_found'}\n    dest = Path(output_dir) / Path(path).stem\n    dest.mkdir(parents=True, exist_ok=True)\n    with zipfile.ZipFile(path) as zf:\n        zf.extractall(str(dest))\n        names = zf.namelist()\n    files = [str(dest/n) for n in names if (dest/n).is_file()]\n    return {'ok': True, 'output': 'Извлечено ' + str(len(files)) + ' файлов в ' + str(dest), 'files': files[:20], 'error': ''}"
)

_T['shell_cmd'] = (
    'Выполнить shell-команду',
    "def run_tool(inputs):\n    import subprocess\n    cmd = inputs.get('cmd', inputs.get('command','')).strip()\n    cwd = inputs.get('cwd','') or None\n    timeout = int(inputs.get('timeout',30))\n    if not cmd:\n        return {'ok': False, 'output': 'Нужен cmd', 'files': [], 'error': 'missing'}\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8','cp1251','latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    r = subprocess.run(cmd, shell=True, capture_output=True, timeout=timeout, cwd=cwd)\n    out = (_d(r.stdout)+_d(r.stderr)).strip()\n    return {'ok': r.returncode==0, 'output': out[:3000], 'files': [], 'error': out[:500] if r.returncode else ''}"
)

_T['smith_template'] = (
    'АГЕНТ_СМИТ pipeline — создаёт проект по задаче',
    "def run_tool(inputs):\n    import os, sys, time\n    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))\n    task = inputs.get('task','').strip()\n    output_dir = inputs.get('output_dir','/tmp')\n    if not task:\n        return {'ok': False, 'output': 'Нужен task', 'files': [], 'error': 'missing'}\n    try:\n        from agent_session import create_session, execute_pipeline, close_session, STAGE_WAIT_FILES\n        from pathlib import Path\n        cid = 'neo_' + str(int(time.time()))\n        sess = create_session(cid)\n        sess.task = task; sess.stage = STAGE_WAIT_FILES\n        sess.output_dir = str(Path(output_dir) / ('smith_' + str(int(time.time()))))\n        os.makedirs(sess.output_dir, exist_ok=True)\n        result = execute_pipeline(sess, on_status=lambda m: print(m))\n        close_session(cid)\n        files = [a['path'] for a in result.get('artifacts',[]) if os.path.exists(a.get('path',''))]\n        if result.get('zip_path') and os.path.exists(result['zip_path']):\n            files.insert(0, result['zip_path'])\n        return {'ok': result.get('ok', bool(files)), 'output': 'СМИТ: ' + str(len(files)) + ' файлов', 'files': files, 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['html_scraper'] = (
    'Извлечь текст с веб-страницы (alias web_scraper)',
    "def run_tool(inputs):\n    import urllib.request, re\n    from pathlib import Path\n    url = inputs.get('url', inputs.get('link', '')).strip()\n    output_dir = inputs.get('output_dir', '/tmp')\n    if not url: return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    try:\n        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n        with urllib.request.urlopen(req, timeout=15) as r:\n            html = r.read(200000).decode('utf-8', 'replace')\n        text = re.sub(r'<[^>]+>', ' ', html)\n        text = re.sub(r' +', ' ', text).strip()[:8000]\n        out = Path(output_dir) / ('page_' + str(abs(hash(url)) % 99999) + '.txt')\n        out.write_text(text, encoding='utf-8')\n        return {'ok': True, 'output': text[:3000], 'files': [str(out)], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['text_extractor'] = (
    'Извлечь и очистить текст из URL или файла',
    "def run_tool(inputs):\n    import urllib.request, re, os\n    from pathlib import Path\n    url  = inputs.get('url', inputs.get('link', '')).strip()\n    path = inputs.get('path', inputs.get('file_path', '')).strip()\n    output_dir = inputs.get('output_dir', '/tmp')\n    if url:\n        try:\n            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n            with urllib.request.urlopen(req, timeout=15) as r:\n                raw = r.read(200000).decode('utf-8', 'replace')\n            text = re.sub(r'<[^>]+>', ' ', raw)\n            text = re.sub(r' +', ' ', text).strip()[:8000]\n        except Exception as e:\n            return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}\n    elif path and os.path.exists(path):\n        for enc in ('utf-8', 'cp1251', 'latin-1'):\n            try: text = open(path, encoding=enc).read()[:8000]; break\n            except UnicodeDecodeError: continue\n        else: return {'ok': False, 'output': 'Не удалось декодировать', 'files': [], 'error': 'decode'}\n    else:\n        return {'ok': False, 'output': 'Нужен url или path', 'files': [], 'error': 'missing'}\n    src = url or path\n    out = Path(output_dir) / ('extracted_' + str(abs(hash(src)) % 99999) + '.txt')\n    out.write_text(text, encoding='utf-8')\n    return {'ok': True, 'output': text[:3000], 'files': [str(out)], 'error': ''}"
)

_T['http_get'] = (
    'HTTP GET запрос к API или URL',
    "def run_tool(inputs):\n    import urllib.request, urllib.parse, json as _j\n    url     = inputs.get('url', '').strip()\n    params  = inputs.get('params', inputs.get('query', {}))\n    headers = inputs.get('headers', {})\n    if not url: return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    if params and isinstance(params, dict):\n        url = url + ('&' if '?' in url else '?') + urllib.parse.urlencode(params)\n    try:\n        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0', **headers})\n        with urllib.request.urlopen(req, timeout=15) as r:\n            body = r.read(100000).decode('utf-8', 'replace')\n        try: result = _j.dumps(_j.loads(body), ensure_ascii=False, indent=2)[:4000]\n        except: result = body[:4000]\n        return {'ok': True, 'output': result, 'files': [], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['http_post'] = (
    'HTTP POST запрос к API',
    "def run_tool(inputs):\n    import urllib.request, json as _j\n    url     = inputs.get('url', '').strip()\n    data    = inputs.get('data', inputs.get('body', {}))\n    headers = inputs.get('headers', {})\n    if not url: return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    body = _j.dumps(data).encode() if isinstance(data, dict) else str(data).encode()\n    try:\n        h = {'Content-Type': 'application/json', 'User-Agent': 'Mozilla/5.0', **headers}\n        req = urllib.request.Request(url, data=body, headers=h, method='POST')\n        with urllib.request.urlopen(req, timeout=15) as r:\n            resp = r.read(100000).decode('utf-8', 'replace')\n        try: result = _j.dumps(_j.loads(resp), ensure_ascii=False, indent=2)[:4000]\n        except: result = resp[:4000]\n        return {'ok': True, 'output': result, 'files': [], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['requirements_installer'] = (
    'Установить зависимости из requirements.txt файла или списка пакетов',
    "def run_tool(inputs):\n    import subprocess, sys, os\n    from pathlib import Path\n    # Принимает файл requirements.txt или список пакетов\n    req_file = inputs.get('requirements_file', inputs.get('requirements_path', inputs.get('path', '')))\n    packages = inputs.get('packages', inputs.get('package', ''))\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8', 'cp1251', 'latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    if req_file and os.path.exists(str(req_file)):\n        r = subprocess.run([sys.executable, '-m', 'pip', 'install', '-r', str(req_file), '-q', '--break-system-packages'],\n                           capture_output=True, timeout=300)\n        out = _d(r.stdout) + _d(r.stderr)\n        ok = r.returncode == 0\n        return {'ok': ok, 'output': ('OK' if ok else 'FAIL') + ': ' + str(req_file) + chr(10) + out[:500], 'files': [], 'error': '' if ok else out[:300]}\n    elif packages:\n        if isinstance(packages, str): pkg_list = packages.split()\n        elif isinstance(packages, list): pkg_list = packages\n        else: pkg_list = [str(packages)]\n        r = subprocess.run([sys.executable, '-m', 'pip', 'install', '--break-system-packages', '-q'] + pkg_list,\n                           capture_output=True, timeout=300)\n        out = _d(r.stdout) + _d(r.stderr)\n        ok = r.returncode == 0\n        return {'ok': ok, 'output': ('OK' if ok else 'FAIL') + ': ' + ' '.join(pkg_list) + chr(10) + out[:500], 'files': [], 'error': '' if ok else out[:300]}\n    else:\n        return {'ok': False, 'output': 'Нужен requirements_file или packages', 'files': [], 'error': 'missing'}"
)

_T['run_script'] = (
    'Запустить Python скрипт или shell-команду',
    "def run_tool(inputs):\n    import subprocess, sys, tempfile, os\n    script   = inputs.get('script', inputs.get('code', inputs.get('cmd', ''))).strip()\n    lang     = inputs.get('lang', 'python').lower()\n    cwd      = inputs.get('cwd', inputs.get('workdir', ''))\n    timeout  = int(inputs.get('timeout', 60))\n    output_dir = inputs.get('output_dir', '/tmp')\n    if not script: return {'ok': False, 'output': 'Нужен script', 'files': [], 'error': 'missing'}\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8', 'cp1251', 'latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    if lang in ('sh', 'bash', 'shell'):\n        r = subprocess.run(script, shell=True, capture_output=True, timeout=timeout, cwd=cwd or output_dir)\n        out = (_d(r.stdout) + _d(r.stderr)).strip()\n        return {'ok': r.returncode == 0, 'output': out[:3000], 'files': [], 'error': out[:500] if r.returncode else ''}\n    else:\n        with tempfile.NamedTemporaryFile('w', suffix='.py', delete=False, encoding='utf-8') as f:\n            f.write(script); tmp = f.name\n        try:\n            r = subprocess.run([sys.executable, tmp], capture_output=True, timeout=timeout, cwd=cwd or output_dir)\n            out = (_d(r.stdout) + _d(r.stderr)).strip()\n            return {'ok': r.returncode == 0, 'output': out[:3000], 'files': [], 'error': _d(r.stderr) if r.returncode else ''}\n        finally:\n            try: os.unlink(tmp)\n            except: pass"
)

_T['git_info'] = (
    'Получить информацию о Git репозитории или клонировать',
    "def run_tool(inputs):\n    import subprocess, os\n    from pathlib import Path\n    url    = inputs.get('url', inputs.get('repo', '')).strip()\n    action = inputs.get('action', 'info').lower()\n    cwd    = inputs.get('path', inputs.get('cwd', '.'))\n    output_dir = inputs.get('output_dir', '/tmp')\n    def _d(b):\n        if not b: return ''\n        for e in ('utf-8', 'cp1251', 'latin-1'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode('utf-8', errors='replace')\n    if action == 'clone' and url:\n        name = url.rstrip('/').split('/')[-1].replace('.git', '')\n        dest = str(Path(output_dir) / name)\n        r = subprocess.run(['git', 'clone', '--depth=1', url, dest], capture_output=True, timeout=120)\n        out = _d(r.stdout) + _d(r.stderr)\n        return {'ok': r.returncode == 0, 'output': out, 'files': [dest] if r.returncode == 0 else [], 'error': '' if r.returncode == 0 else out}\n    elif url and 'github.com' in url:\n        import urllib.request, json as _j\n        try:\n            parts = url.rstrip('/').replace('https://github.com/', '').split('/')\n            api = 'https://api.github.com/repos/' + '/'.join(parts[:2])\n            req = urllib.request.Request(api, headers={'User-Agent': 'Mozilla/5.0'})\n            with urllib.request.urlopen(req, timeout=10) as resp:\n                info = _j.loads(resp.read())\n            out = 'Репо: ' + info.get('full_name', '') + chr(10) + 'Stars: ' + str(info.get('stargazers_count', 0)) + chr(10) + info.get('description', '')\n            return {'ok': True, 'output': out, 'files': [], 'error': ''}\n        except Exception as e:\n            return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}\n    else:\n        r = subprocess.run(['git', 'log', '--oneline', '-10'], capture_output=True, timeout=10, cwd=cwd)\n        out = _d(r.stdout) + _d(r.stderr)\n        return {'ok': r.returncode == 0, 'output': out[:2000], 'files': [], 'error': ''}"
)

_T['rss_parser'] = (
    'Парсинг RSS/Atom лент',
    "def run_tool(inputs):\n    import urllib.request, re\n    from pathlib import Path\n    url = inputs.get('url', '').strip()\n    limit = int(inputs.get('limit', 10))\n    output_dir = inputs.get('output_dir', '/tmp')\n    if not url: return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    try:\n        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})\n        with urllib.request.urlopen(req, timeout=15) as r:\n            xml = r.read(200000).decode('utf-8', 'replace')\n        items = re.findall(r'<item[^>]*>(.*?)</item>', xml, re.DOTALL)\n        if not items: items = re.findall(r'<entry[^>]*>(.*?)</entry>', xml, re.DOTALL)\n        results = []\n        for item in items[:limit]:\n            title = re.search(r'<title[^>]*>(.*?)</title>', item, re.DOTALL)\n            link  = re.search(r'<link[^>]*>(.*?)</link>',  item, re.DOTALL)\n            desc  = re.search(r'<description[^>]*>(.*?)</description>', item, re.DOTALL)\n            t = re.sub(r'<[^>]+>', '', title.group(1) if title else '').strip()\n            l = re.sub(r'<[^>]+>', '', link.group(1)  if link  else '').strip()\n            d = re.sub(r'<[^>]+>', '', desc.group(1)  if desc  else '').strip()[:200]\n            results.append(t + chr(10) + l + chr(10) + d)\n        text = chr(10) + '---' + chr(10) + chr(10).join(results)\n        out_file = Path(output_dir) / ('rss_' + str(abs(hash(url)) % 99999) + '.txt')\n        out_file.write_text(text, encoding='utf-8')\n        return {'ok': bool(results), 'output': text[:3000], 'files': [str(out_file)], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['csv_reader'] = (
    'Читать CSV файл',
    "def run_tool(inputs):\n    import csv, json as _j, os\n    path  = inputs.get('path', inputs.get('file_path', '')).strip()\n    limit = int(inputs.get('limit', 100))\n    if not path or not os.path.exists(path):\n        return {'ok': False, 'output': 'Не найден: ' + path, 'files': [], 'error': 'not_found'}\n    try:\n        rows = []\n        for enc in ('utf-8', 'cp1251', 'latin-1'):\n            try:\n                with open(path, encoding=enc, newline='') as f:\n                    rows = list(csv.DictReader(f))[:limit]\n                break\n            except UnicodeDecodeError: continue\n        out = _j.dumps(rows[:10], ensure_ascii=False, indent=2)\n        return {'ok': True, 'output': 'Строк: ' + str(len(rows)) + chr(10) + out[:3000], 'files': [path], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['csv_writer'] = (
    'Записать данные в CSV файл',
    "def run_tool(inputs):\n    import csv, json as _j, os\n    from pathlib import Path\n    data   = inputs.get('data', inputs.get('rows', []))\n    path   = inputs.get('path', '')\n    output_dir = inputs.get('output_dir', '/tmp')\n    if not path: path = str(Path(output_dir) / 'output.csv')\n    if isinstance(data, str):\n        try: data = _j.loads(data)\n        except: return {'ok': False, 'output': 'data должен быть список', 'files': [], 'error': 'invalid_data'}\n    if not isinstance(data, list) or not data:\n        return {'ok': False, 'output': 'Нужен непустой список data', 'files': [], 'error': 'empty'}\n    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)\n    fields = list(data[0].keys()) if isinstance(data[0], dict) else list(range(len(data[0])))\n    with open(path, 'w', newline='', encoding='utf-8') as f:\n        if isinstance(data[0], dict):\n            w = csv.DictWriter(f, fieldnames=fields); w.writeheader(); w.writerows(data)\n        else:\n            csv.writer(f).writerows(data)\n    return {'ok': True, 'output': 'Записано строк: ' + str(len(data)) + ' -> ' + path, 'files': [path], 'error': ''}"
)

_T['json_transformer'] = (
    'Преобразовать JSON данные',
    "def run_tool(inputs):\n    import json as _j, os\n    from pathlib import Path\n    data    = inputs.get('data', inputs.get('json', ''))\n    action  = inputs.get('action', 'pretty').lower()\n    key     = inputs.get('key', inputs.get('field', ''))\n    output_dir = inputs.get('output_dir', '/tmp')\n    if isinstance(data, str):\n        try: data = _j.loads(data)\n        except Exception as e: return {'ok': False, 'output': 'Ошибка парсинга JSON: ' + str(e), 'files': [], 'error': str(e)}\n    if action == 'extract' and key:\n        if isinstance(data, list): result = [item.get(key) for item in data if isinstance(item, dict)]\n        else: result = data.get(key)\n    elif action == 'keys' and isinstance(data, (dict, list)):\n        result = list(data[0].keys()) if isinstance(data, list) and data else list(data.keys()) if isinstance(data, dict) else []\n    elif action == 'count':\n        result = len(data) if isinstance(data, (list, dict)) else 1\n    else:\n        result = data\n    out_str = _j.dumps(result, ensure_ascii=False, indent=2)\n    out_file = Path(output_dir) / 'transformed.json'\n    out_file.write_text(out_str, encoding='utf-8')\n    return {'ok': True, 'output': out_str[:3000], 'files': [str(out_file)], 'error': ''}"
)

_T['pdf_reader'] = (
    'Читать PDF файл',
    'def run_tool(inputs):\n    import subprocess, sys, os\n    from pathlib import Path\n    path = inputs.get(\'path\', inputs.get(\'file_path\', \'\')).strip()\n    output_dir = inputs.get(\'output_dir\', \'/tmp\')\n    if not path or not os.path.exists(path):\n        return {\'ok\': False, \'output\': \'Не найден: \' + path, \'files\': [], \'error\': \'not_found\'}\n    def _d(b):\n        if not b: return \'\'\n        for e in (\'utf-8\', \'cp1251\', \'latin-1\'):\n            try: return b.decode(e)\n            except: pass\n        return b.decode(\'utf-8\', errors=\'replace\')\n    try:\n        r = subprocess.run([sys.executable, \'-c\',\n            \'import sys; from pypdf import PdfReader; p=PdfReader(sys.argv[1]); print(chr(10).join(pg.extract_text() or "" for pg in p.pages[:10]))\',\n            path], capture_output=True, timeout=30)\n        if r.returncode == 0 and r.stdout:\n            text = _d(r.stdout)[:5000]\n            out = Path(output_dir) / (Path(path).stem + \'.txt\')\n            out.write_text(text, encoding=\'utf-8\')\n            return {\'ok\': True, \'output\': text[:3000], \'files\': [str(out)], \'error\': \'\'}\n    except: pass\n    # Fallback: pdfminer\n    try:\n        r2 = subprocess.run([sys.executable, \'-c\',\n            \'from pdfminer.high_level import extract_text; print(extract_text("\' + path + \'")[:5000])\'],\n            capture_output=True, timeout=30)\n        text = _d(r2.stdout)[:5000]\n        if text.strip():\n            out = Path(output_dir) / (Path(path).stem + \'.txt\')\n            out.write_text(text, encoding=\'utf-8\')\n            return {\'ok\': True, \'output\': text[:3000], \'files\': [str(out)], \'error\': \'\'}\n    except: pass\n    return {\'ok\': False, \'output\': \'PDF читалка недоступна. Установи: pip install pypdf\', \'files\': [], \'error\': \'no_pdf_lib\'}'
)

_T['file_search'] = (
    'Поиск файлов по имени или расширению',
    "def run_tool(inputs):\n    import os, fnmatch\n    search_dir = inputs.get('dir', inputs.get('path', '.')).strip()\n    pattern    = inputs.get('pattern', inputs.get('name', '*')).strip()\n    ext        = inputs.get('ext', '').strip().lstrip('.')\n    if ext and not pattern.endswith('.' + ext): pattern = '*.' + ext\n    results = []\n    try:\n        for root, dirs, files in os.walk(search_dir):\n            dirs[:] = [d for d in dirs if not d.startswith('.') and d != '__pycache__']\n            for f in files:\n                if fnmatch.fnmatch(f.lower(), pattern.lower()):\n                    results.append(os.path.join(root, f))\n        if not results:\n            return {'ok': True, 'output': 'Файлы не найдены по паттерну: ' + pattern, 'files': [], 'error': ''}\n        text = 'Найдено ' + str(len(results)) + ' файлов:' + chr(10) + chr(10).join(results[:50])\n        return {'ok': True, 'output': text, 'files': results[:20], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['analyze_code'] = (
    'Анализ Python кода на ошибки и улучшения',
    "def run_tool(inputs):\n    import ast, sys, os\n    from pathlib import Path\n    code = inputs.get('code', '')\n    path = inputs.get('path', '')\n    output_dir = inputs.get('output_dir', '/tmp')\n    if path and os.path.exists(path):\n        code = open(path, encoding='utf-8', errors='replace').read()\n    if not code:\n        return {'ok': False, 'output': 'Нужен code или path', 'files': [], 'error': 'missing'}\n    issues = []\n    try:\n        ast.parse(code)\n        issues.append('Синтаксис: OK')\n    except SyntaxError as e:\n        issues.append('SyntaxError строка ' + str(e.lineno) + ': ' + str(e.msg))\n    lines = code.split(chr(10))\n    for i, l in enumerate(lines, 1):\n        if 'except:' in l or 'except Exception:' in l:\n            issues.append('Строка ' + str(i) + ': голый except — поймает всё')\n        if 'print(' in l and '#' not in l.split('print')[0]:\n            issues.append('Строка ' + str(i) + ': print() — убери в продакшене')\n    report = chr(10).join(issues) + chr(10) + chr(10) + 'Строк кода: ' + str(len(lines))\n    out = Path(output_dir) / 'analysis.txt'\n    out.write_text(report, encoding='utf-8')\n    return {'ok': True, 'output': report, 'files': [str(out)], 'error': ''}"
)

_T['data_aggregator'] = (
    'Агрегация и суммаризация данных',
    "def run_tool(inputs):\n    import json as _j, os\n    from pathlib import Path\n    data   = inputs.get('data', inputs.get('items', []))\n    action = inputs.get('action', 'summary').lower()\n    output_dir = inputs.get('output_dir', '/tmp')\n    if isinstance(data, str):\n        try: data = _j.loads(data)\n        except: data = data.split(chr(10))\n    if not isinstance(data, list): data = [data]\n    if action == 'count': result = {'count': len(data)}\n    elif action == 'unique': result = list(set(str(x) for x in data))\n    elif action == 'join': result = chr(10).join(str(x) for x in data)\n    else: result = {'count': len(data), 'first': data[:3] if data else [], 'last': data[-3:] if len(data) > 3 else []}\n    out_str = _j.dumps(result, ensure_ascii=False, indent=2) if not isinstance(result, str) else result\n    out = Path(output_dir) / 'aggregated.json'\n    out.write_text(out_str, encoding='utf-8')\n    return {'ok': True, 'output': out_str[:3000], 'files': [str(out)], 'error': ''}"
)

_T['dedup_tool'] = (
    'Удаление дублирующихся записей',
    "def run_tool(inputs):\n    import json as _j\n    from pathlib import Path\n    data   = inputs.get('data', inputs.get('items', []))\n    key    = inputs.get('key', '')\n    output_dir = inputs.get('output_dir', '/tmp')\n    if isinstance(data, str):\n        try: data = _j.loads(data)\n        except: data = [l.strip() for l in data.split(chr(10)) if l.strip()]\n    seen = set(); result = []\n    for item in data:\n        val = item.get(key, str(item)) if key and isinstance(item, dict) else str(item)\n        if val not in seen: seen.add(val); result.append(item)\n    out_str = _j.dumps(result, ensure_ascii=False, indent=2)\n    out = Path(output_dir) / 'deduped.json'\n    out.write_text(out_str, encoding='utf-8')\n    removed = len(data) - len(result)\n    return {'ok': True, 'output': 'Было: ' + str(len(data)) + ', стало: ' + str(len(result)) + ', убрано: ' + str(removed) + chr(10) + out_str[:2000], 'files': [str(out)], 'error': ''}"
)

_T['diff_tool'] = (
    'Сравнение двух текстов/файлов',
    "def run_tool(inputs):\n    import difflib, os\n    from pathlib import Path\n    a      = inputs.get('a', inputs.get('text1', inputs.get('old', '')))\n    b      = inputs.get('b', inputs.get('text2', inputs.get('new', '')))\n    path_a = inputs.get('path_a', inputs.get('file1', ''))\n    path_b = inputs.get('path_b', inputs.get('file2', ''))\n    output_dir = inputs.get('output_dir', '/tmp')\n    if path_a and os.path.exists(path_a): a = open(path_a, encoding='utf-8', errors='replace').read()\n    if path_b and os.path.exists(path_b): b = open(path_b, encoding='utf-8', errors='replace').read()\n    if not a or not b: return {'ok': False, 'output': 'Нужны a и b', 'files': [], 'error': 'missing'}\n    diff = list(difflib.unified_diff(a.splitlines(), b.splitlines(), lineterm=''))\n    diff_text = chr(10).join(diff[:200])\n    out = Path(output_dir) / 'diff.txt'\n    out.write_text(diff_text, encoding='utf-8')\n    return {'ok': True, 'output': diff_text[:3000] or 'Файлы идентичны', 'files': [str(out)], 'error': ''}"
)

_T['api_caller'] = (
    'Универсальный HTTP вызов к любому API',
    "def run_tool(inputs):\n    import urllib.request, urllib.parse, json as _j\n    url     = inputs.get('url', inputs.get('endpoint', '')).strip()\n    method  = inputs.get('method', 'GET').upper()\n    data    = inputs.get('data', inputs.get('body', inputs.get('payload', None)))\n    headers = inputs.get('headers', {})\n    params  = inputs.get('params', inputs.get('query_params', {}))\n    if not url: return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    if params and isinstance(params, dict):\n        url = url + ('&' if '?' in url else '?') + urllib.parse.urlencode(params)\n    body = None\n    if data is not None:\n        if isinstance(data, dict): body = _j.dumps(data).encode(); headers.setdefault('Content-Type', 'application/json')\n        else: body = str(data).encode()\n    try:\n        h = {'User-Agent': 'Mozilla/5.0', **headers}\n        req = urllib.request.Request(url, data=body, headers=h, method=method)\n        with urllib.request.urlopen(req, timeout=15) as r:\n            resp = r.read(100000).decode('utf-8', 'replace')\n        try: result = _j.dumps(_j.loads(resp), ensure_ascii=False, indent=2)[:4000]\n        except: result = resp[:4000]\n        return {'ok': True, 'output': result, 'files': [], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['send_mail'] = (
    'Отправить email через SMTP или Telegram уведомление',
    "def run_tool(inputs):\n    import smtplib, os\n    from email.mime.text import MIMEText\n    to      = inputs.get('to', inputs.get('email', '')).strip()\n    subject = inputs.get('subject', 'NEO Report')\n    body    = inputs.get('body', inputs.get('text', inputs.get('content', '')))\n    smtp    = inputs.get('smtp', os.environ.get('SMTP_HOST', 'smtp.gmail.com'))\n    port    = int(inputs.get('port', 587))\n    user    = inputs.get('user', os.environ.get('SMTP_USER', ''))\n    pwd     = inputs.get('password', os.environ.get('SMTP_PASS', ''))\n    if not to: return {'ok': False, 'output': 'Нужен email получателя (to)', 'files': [], 'error': 'missing'}\n    if not body: return {'ok': False, 'output': 'Нужен body', 'files': [], 'error': 'missing'}\n    if not user or not pwd:\n        note = 'Email не отправлен (нет SMTP_USER/SMTP_PASS в .env).' + chr(10) + 'Сохранён отчёт:'\n        return {'ok': False, 'output': note + chr(10) + str(body)[:500], 'files': [], 'error': 'no_credentials'}\n    try:\n        msg = MIMEText(str(body), 'plain', 'utf-8')\n        msg['Subject'] = str(subject)\n        msg['From']    = user\n        msg['To']      = to\n        with smtplib.SMTP(smtp, port) as s:\n            s.starttls(); s.login(user, pwd); s.send_message(msg)\n        return {'ok': True, 'output': 'Email отправлен на ' + to, 'files': [], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['telegram_notify'] = (
    'Отправить уведомление в Telegram',
    "def run_tool(inputs):\n    import urllib.request, urllib.parse, json as _j, os\n    token   = inputs.get('token', os.environ.get('BOT_TOKEN', os.environ.get('TELEGRAM_BOT_TOKEN', '')))\n    chat_id = inputs.get('chat_id', inputs.get('to', os.environ.get('TELEGRAM_CHAT_ID', '')))\n    text    = inputs.get('text', inputs.get('message', inputs.get('body', '')))\n    if not token: return {'ok': False, 'output': 'Нужен BOT_TOKEN в .env или в inputs', 'files': [], 'error': 'no_token'}\n    if not chat_id: return {'ok': False, 'output': 'Нужен chat_id', 'files': [], 'error': 'no_chat_id'}\n    if not text: return {'ok': False, 'output': 'Нужен text', 'files': [], 'error': 'missing'}\n    try:\n        url = 'https://api.telegram.org/bot' + token + '/sendMessage'\n        data = _j.dumps({'chat_id': chat_id, 'text': str(text)[:4000]}).encode()\n        req = urllib.request.Request(url, data=data, headers={'Content-Type': 'application/json'})\n        with urllib.request.urlopen(req, timeout=10) as r:\n            resp = _j.loads(r.read())\n        if resp.get('ok'): return {'ok': True, 'output': 'Отправлено в ' + str(chat_id), 'files': [], 'error': ''}\n        return {'ok': False, 'output': str(resp), 'files': [], 'error': str(resp)}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['webhook_sender'] = (
    'Отправить данные на webhook URL',
    "def run_tool(inputs):\n    import urllib.request, json as _j\n    url     = inputs.get('url', inputs.get('webhook_url', inputs.get('endpoint', ''))).strip()\n    data    = inputs.get('data', inputs.get('payload', inputs.get('body', {})))\n    headers = inputs.get('headers', {})\n    if not url: return {'ok': False, 'output': 'Нужен url', 'files': [], 'error': 'missing'}\n    if isinstance(data, dict): body = _j.dumps(data).encode(); headers.setdefault('Content-Type', 'application/json')\n    else: body = str(data).encode()\n    try:\n        req = urllib.request.Request(url, data=body, headers={'User-Agent': 'NEO/1.0', **headers}, method='POST')\n        with urllib.request.urlopen(req, timeout=15) as r:\n            resp = r.read(1000).decode('utf-8', 'replace')\n        return {'ok': True, 'output': 'Webhook OK: ' + resp[:200], 'files': [], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['image_gen'] = (
    'Генерация изображения по описанию (Pollinations или PIL)',
    "def run_tool(inputs):\n    import sys, os\n    from pathlib import Path\n    sys.path.insert(0, str(Path(__file__).parent.parent))\n    prompt = inputs.get('prompt', inputs.get('text', inputs.get('description', ''))).strip()\n    output_dir = inputs.get('output_dir', '/tmp')\n    if not prompt: return {'ok': False, 'output': 'Нужен prompt', 'files': [], 'error': 'missing'}\n    try:\n        from agent_tools_registry import tool_pollinations_image\n        result = tool_pollinations_image({'prompt': prompt, 'output_dir': output_dir})\n        import re\n        m = re.search(r'([\\w/\\\\. -]+\\.(?:jpg|png|gif|webp))', str(result))\n        files = [m.group(1)] if m and os.path.exists(m.group(1)) else []\n        return {'ok': True, 'output': str(result)[:500], 'files': files, 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': str(e), 'files': [], 'error': str(e)}"
)

_T['tts_speak'] = (
    'Синтез речи: текст → MP3',
    "def run_tool(inputs):\n    import sys, os\n    from pathlib import Path\n    sys.path.insert(0, str(Path(__file__).parent.parent))\n    text = inputs.get('text', inputs.get('message', '')).strip()\n    output_dir = inputs.get('output_dir', '/tmp')\n    lang = inputs.get('lang', inputs.get('language', 'ru'))\n    voice = inputs.get('voice', '')\n    if not text: return {'ok': False, 'output': 'Нужен text', 'files': [], 'error': 'missing'}\n    out_path = str(Path(output_dir) / ('tts_' + str(abs(hash(text)) % 99999) + '.mp3'))\n    try:\n        from tts_engine import tts_generate\n        ok = tts_generate(text, out_path, lang=lang)\n        if ok and os.path.exists(out_path):\n            return {'ok': True, 'output': 'Озвучено: ' + out_path, 'files': [out_path], 'error': ''}\n    except Exception: pass\n    try:\n        import asyncio, edge_tts\n        vc = voice or ('ru-RU-DmitryNeural' if lang == 'ru' else 'en-US-ChristopherNeural')\n        async def _tts():\n            comm = edge_tts.Communicate(text, vc)\n            await comm.save(out_path)\n        asyncio.run(_tts())\n        if os.path.exists(out_path):\n            return {'ok': True, 'output': 'Озвучено (edge-tts): ' + out_path, 'files': [out_path], 'error': ''}\n    except Exception as e:\n        return {'ok': False, 'output': 'TTS недоступен: ' + str(e), 'files': [], 'error': str(e)}\n    return {'ok': False, 'output': 'TTS недоступен', 'files': [], 'error': 'no_tts'}"
)


def register_all(on_status=None, llm_generate_missing=False):
    """Регистрирует все встроенные инструменты NEO."""
    try:
        sys.path.insert(0, str(BASE_DIR))
        from agent_neo import register_tool, tool_exists
    except ImportError as e:
        if on_status: on_status("agent_neo недоступен: " + str(e))
        return {"registered": 0, "skipped": 0, "generated": 0, "failed": 0}
    registered = skipped = failed = 0
    for name, (desc, code) in _T.items():
        try:
            if tool_exists(name):
                skipped += 1
                continue
            register_tool(name, desc, code.strip(), builtin=True)
            registered += 1
            if on_status: on_status("  + " + name)
        except Exception as e:
            failed += 1
            if on_status: on_status("  ! " + name + ": " + str(e))
    msg = "NEO tools: +" + str(registered) + " / skip=" + str(skipped) + " / err=" + str(failed)
    if on_status: on_status(msg)
    return {"registered": registered, "skipped": skipped, "generated": 0, "failed": failed}


def test_all(on_status=None):
    """Тестирует все инструменты."""
    passed = []; failed = []
    try:
        sys.path.insert(0, str(BASE_DIR))
        from agent_neo import list_tools, sandbox_run
        for t in list_tools():
            ok, out, _ = sandbox_run(t["code"], {"output_dir": "/tmp"}, timeout=10)
            (passed if ok or "missing" in out.lower() else failed).append(t["name"])
    except Exception as e:
        failed.append(str(e))
    return {"passed": passed, "failed": failed}