# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Dict, List

from .tools_adapter import Coder3ToolAdapter


def _infer_python_filename(task_text: str) -> str:
    low = (task_text or '').lower()
    if 'телеграм' in low and 'бот' in low:
        return 'quick_bot/bot.py'
    if 'snow' in low or 'снег' in low or 'gif' in low:
        return 'quick_task/snowfall_gif.py'
    if 'анимац' in low or 'matrix' in low or 'матриц' in low:
        return 'quick_task/matrix_animation.py'
    if 'parser' in low or 'парсер' in low:
        return 'quick_task/parser.py'
    if 'api' in low:
        return 'quick_task/api_client.py'
    return 'quick_task/task.py'


def _matrix_template() -> str:
    return '''import random
import shutil
import sys
import time

CHARS = "01アイウエオカキクケコサシスセソ"


def clear():
    sys.stdout.write("\\x1b[2J\\x1b[H")


def frame(width: int, height: int) -> str:
    rows = []
    for _ in range(height):
        row = "".join(random.choice(CHARS) if random.random() > 0.82 else " " for _ in range(width))
        rows.append(row)
    return "\\n".join(rows)


def main() -> None:
    size = shutil.get_terminal_size((80, 24))
    width, height = min(size.columns, 100), min(size.lines - 1, 28)
    for _ in range(60):
        clear()
        print(frame(width, height))
        time.sleep(0.08)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
'''


def _snowfall_template() -> str:
    return '''import random
from PIL import Image, ImageDraw

WIDTH = 256
HEIGHT = 256
NUM_SNOWFLAKES = 70
NUM_FRAMES = 36
BACKGROUND = (8, 16, 40)
SNOW = (255, 255, 255)


class Snowflake:
    def __init__(self):
        self.reset(initial=True)

    def reset(self, initial: bool = False):
        self.x = random.randint(0, WIDTH - 1)
        self.y = random.randint(0, HEIGHT - 1) if initial else random.randint(-30, 0)
        self.size = random.randint(1, 3)
        self.speed = random.uniform(1.0, 3.2)
        self.wind = random.uniform(-0.7, 0.7)

    def step(self):
        self.y += self.speed
        self.x += self.wind
        if self.y >= HEIGHT:
            self.reset(initial=False)
        if self.x < 0:
            self.x = WIDTH - 1
        elif self.x >= WIDTH:
            self.x = 0


def make_frame(snowflakes):
    img = Image.new("RGB", (WIDTH, HEIGHT), BACKGROUND)
    draw = ImageDraw.Draw(img)
    for flake in snowflakes:
        x0 = flake.x - flake.size
        y0 = flake.y - flake.size
        x1 = flake.x + flake.size
        y1 = flake.y + flake.size
        draw.ellipse((x0, y0, x1, y1), fill=SNOW)
        flake.step()
    return img


def main():
    flakes = [Snowflake() for _ in range(NUM_SNOWFLAKES)]
    frames = [make_frame(flakes) for _ in range(NUM_FRAMES)]
    frames[0].save(
        "snowfall.gif",
        save_all=True,
        append_images=frames[1:],
        duration=70,
        loop=0,
    )
    print("saved snowfall.gif")


if __name__ == "__main__":
    main()
'''


def _quick_template(task_text: str) -> str:
    low = (task_text or '').lower()
    if 'телеграм' in low and 'бот' in low:
        return (
            'import os\n'
            'import telebot\n\n'
            'TOKEN = os.getenv("BOT_TOKEN", "")\n'
            'bot = telebot.TeleBot(TOKEN, parse_mode="HTML")\n\n'
            '@bot.message_handler(commands=["start", "help"])\n'
            'def start(message):\n'
            '    bot.reply_to(message, "<b>Привет.</b> Я шаблонный бот от AGENT_CODER3")\n\n'
            'if __name__ == "__main__":\n'
            '    if not TOKEN:\n'
            '        raise SystemExit("BOT_TOKEN is empty")\n'
            '    bot.infinity_polling()\n'
        )
    if 'snow' in low or 'снег' in low or 'gif' in low:
        return _snowfall_template()
    if 'анимац' in low or 'matrix' in low or 'матриц' in low:
        return _matrix_template()
    return (
        '"""Generated by AGENT_CODER3 quick mode."""\n\n'
        'def main():\n'
        f'    task = {task_text!r}\n'
        '    print("Task:", task)\n\n'
        'if __name__ == "__main__":\n'
        '    main()\n'
    )


def run_quick_mode(task_text: str, adapter: Coder3ToolAdapter) -> Dict:
    rel_path = _infer_python_filename(task_text)
    code = _quick_template(task_text)
    adapter.create_file(rel_path, code)
    low = (task_text or '').lower()
    if rel_path.endswith('bot.py'):
        adapter.create_file('quick_bot/requirements.txt', 'pyTelegramBotAPI==4.31.0\npython-dotenv>=1.0\n')
        adapter.create_file('quick_bot/.env.example', 'BOT_TOKEN=your_token_here\n')
        adapter.create_file('quick_bot/README.md', '# Quick Telegram bot\n\nGenerated by AGENT_CODER3.\n')
    elif 'snow' in low or 'снег' in low or 'gif' in low:
        adapter.create_file('quick_task/requirements.txt', 'Pillow>=10.0.0\n')
        adapter.create_file('quick_task/README.md', '# Snowfall GIF\n\nRun: `python snowfall_gif.py`\nResult: `snowfall.gif`\n')
    elif 'анимац' in low or 'matrix' in low or 'матриц' in low:
        adapter.create_file('quick_task/README.md', '# Matrix animation\n\nRun: `python matrix_animation.py`\n')
    check = adapter.check_python(code)
    package = adapter.package_workspace('quick_bundle.zip')
    summary = 'Создан прямой кодерский scaffold и упакован в zip.'
    if 'snow' in low or 'снег' in low or 'gif' in low:
        summary = 'Создан runnable scaffold для snowfall GIF и упакован в zip.'
    elif 'анимац' in low or 'matrix' in low or 'матриц' in low:
        summary = 'Создан runnable scaffold для matrix animation и упакован в zip.'
    return {
        'ok': check['ok'],
        'summary': summary,
        'details': {'syntax': check, 'package': package},
    }


def run_review_mode(task_text: str, adapter: Coder3ToolAdapter) -> Dict:
    findings: List[str] = []
    risks: List[str] = []
    files = adapter.list_project_files(limit=40)
    entries = adapter.scan_entry_points()
    if any(f.endswith('bot.py') for f in files):
        findings.append('Есть bot.py: проверь разбиение на handlers / services / callbacks.')
    if any('agent_tools_registry.py' in f for f in files):
        findings.append('Registry есть: стоит разнести tools по категориям, иначе будет новый монолит.')
    if any('.env' in f for f in files):
        risks.append('Не публикуй .env и live базы в архиве или репозитории.')
    if not entries:
        risks.append('Не найдена явная точка входа. Добавь main.py или задокументируй запуск.')
    if 'traceback' in task_text.lower() or 'ошибка' in task_text.lower():
        findings.append('Для бага нужен полный traceback и файл/модуль, где он стреляет.')
    findings.append('Добавь compile/smoke-check в CI, чтобы ловить синтаксис до запуска.')
    report = {
        'findings': findings,
        'risks': risks,
        'files_sample': files[:15],
        'entry_points': entries,
    }
    adapter.create_file('review/report.json', __import__('json').dumps(report, ensure_ascii=False, indent=2))
    package = adapter.package_workspace('review_bundle.zip')
    return {'ok': True, 'summary': 'Review завершён: собраны находки и риски.', 'details': {'report': report, 'package': package}}


def run_project_mode(task_text: str, adapter: Coder3ToolAdapter) -> Dict:
    files = adapter.list_project_files(limit=40)
    entries = adapter.scan_entry_points()
    readme = (
        '# Project scaffold from AGENT_CODER3\n\n'
        '## Goal\n' + task_text + '\n\n'
        '## Interpretation\n'
        '- multi-step workflow\n'
        '- analyze → edit → validate → package\n\n'
        '## Existing hints\n' + ('\n'.join(f'- {x}' for x in entries) if entries else '- no entry points detected') + '\n\n'
        '## Files sample\n' + ('\n'.join(f'- {x}' for x in files[:20]) if files else '- repository snapshot unavailable') + '\n'
    )
    adapter.create_file('project_scaffold/README.md', readme)
    adapter.create_file('project_scaffold/handlers/__init__.py', '')
    adapter.create_file('project_scaffold/services/__init__.py', '')
    adapter.create_file('project_scaffold/tests/test_smoke.py', 'def test_smoke():\n    assert True\n')
    adapter.create_file('project_scaffold/PLAN.md', '1. Analyze project\n2. Edit files\n3. Validate\n4. Package\n')
    package = adapter.package_workspace('project_bundle.zip')
    return {'ok': True, 'summary': 'Создан проектный scaffold с планом и zip-артефактом.', 'details': {'entry_points': entries, 'package': package}}


def run_sandbox_mode(task_text: str, adapter: Coder3ToolAdapter) -> Dict:
    blocks = adapter.extract_python_blocks(task_text)
    code = blocks[0] if blocks else task_text
    syntax = adapter.check_python(code)
    if not syntax['ok']:
        return {'ok': False, 'summary': 'Sandbox остановлен: код не проходит синтаксис.', 'details': {'syntax': syntax}}
    result = adapter.run_sandbox(code)
    adapter.create_file('sandbox/last_run.py', code)
    adapter.create_file('sandbox/stdout.txt', result.get('stdout', ''))
    adapter.create_file('sandbox/stderr.txt', result.get('stderr', ''))
    package = adapter.package_workspace('sandbox_bundle.zip')
    return {'ok': result.get('ok', False), 'summary': 'Sandbox выполнен, наблюдения собраны.', 'details': {'runtime': result, 'package': package}}
